name: Run tests in simulation

# Run the tests when we push to the main branch
on:
  push:
    branches: [main]

# Default to the burger variant of Turtlebot
env:
  TURTLEBOT3_MODEL: burger

jobs:
  simulation:
    # Run steps with the ROS Noetic container
    container: public.ecr.aws/docker/library/ros:noetic-robot
    runs-on: ubuntu-latest

    # Use bash and our catkin workspace folder
    defaults:
      run:
        shell: bash
        working-directory: catkin_ws/

    steps:
      # check out the code
      - name: checkout
        uses: actions/checkout@v2

      # build our workspace
      - name: Build workspace
        run: |
          source /opt/ros/noetic/setup.bash
          catkin_make

      # install Turtlebot and Gazebo packages
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            ros-noetic-turtlebot3 \
            ros-noetic-turtlebot3-simulations \
            ros-noetic-gazebo-ros-pkgs \
            ros-noetic-gazebo-ros-control

      # run our ROS tests
      - name: Run tests
        run: |
          source devel/setup.bash &&
          rostest my_turtlebot_sim turtlebot_sim.test --text

