name: Run tests in simulation

# Run the tests when we push to the main branch
on:
  push:
    branches: [main]

# Default to the burger variant of Turtlebot
env:
  TURTLEBOT3_MODEL: burger

jobs:
  simulation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [noetic]
        include:
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1

    # Run steps with the ROS Noetic container
    container:
      image: ${{matrix.docker_image}}

    # Use bash and our catkin workspace folder
    defaults:
      run:
        shell: bash
        working-directory: catkin_ws/

    steps:
      # check out the code
      - name: checkout
        uses: actions/checkout@v2

      # build our workspace
      - name: Build workspace
        run: |
          source /opt/ros/noetic/setup.bash
          catkin_make

      # install Turtlebot and Gazebo packages
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            ros-noetic-turtlebot3 \
            ros-noetic-turtlebot3-simulations \
            ros-noetic-gazebo-ros-pkgs \
            ros-noetic-gazebo-ros-control

      # run our ROS tests
      - name: Run tests
        run: |
          source devel/setup.bash &&
          rostest my_turtlebot_sim turtlebot_sim.test --text

